### PR TITLE
feat: add a JWE (Json Web Encryption) plugin in go

### PR DESCRIPTION
**Pull request by ealogar**
This is a plugin in go to decrypt tokens in JWE format (https://tools.ietf.org/html/rfc7516)
It uses a go JOSE (Json Object Signing and Encryption)  library for the decryption
The reason to develop this plugin in go is the lack of a JOSE library in pure LUA, at least I couldnt find one.
It is configured with a private keyset in JWK format (https://tools.ietf.org/html/rfc7517) but it provide a default keyset for testing purposes.
The plugin will analyze the Authorization Bearer and if it contains a JWE, it will decrypt it and replace the Authorization with the decrypted object (usually a JWS signed jwt).
You can put this plugin on top of you go applications combined with standard jwt-tokens lua plugin and begin using encrypted tokens.

### CODE REVIEW

**Comment by ealogar** [comment]
@gszr I am going to prepare a static yaml config so that you can tests the issues that we have been reporting about go plugins:
- stop being called
- high memory consumption
- reload configuration

**Comment by gszr** [comment]
Hey @ealogar. That'd be very helpful, thanks! Are all of those still reproducible in 2.1.0-alpha1?

**Comment by ealogar** [comment]
I will test when the docker version is available ....

**Comment by gszr** [comment]
@ealogar we have Docker images available for 2.1.0alpha here: https://hub.docker.com/r/kong/kong/tags?page=1&name=2.1.0

**Comment by ealogar** [comment]
Then I will test them in our systems underl load. Yesterday evening I looked for them and they were not generated. Thanks

**Comment by ealogar** [comment]
Also @gszr tell me your comments about this plugin and if you want it to be in the repo...

**Comment by gszr** [comment]
@ealogar Although at the moment we aren't adding new plugins into this repository, we'd encourage you to host it in your GitHub account, and we'd gladly link to it from the README. How does that sound?

**Comment by ealogar** [comment]
That sound greate @gszr , I will do today

**Comment by gszr** [comment]
Perfect, @ealogar! I will be closing this for now, then. Feel free to open a new PR with a new section "Community Plugins" in the readme and add your link in there!

**Comment by gszr** [comment]
Also, @ealogar, the declarative configuration file would be of great help, as I'm investigating those issues - CPU consumption, reload, etc.

**Pull request closed without merging**
